# Generated by Django 4.1.5 on 2023-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('owner_id', models.IntegerField()),
                ('addressee_id', models.IntegerField()),
            ],
        ),
    ]
