# Generated by Django 4.1.5 on 2023-01-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0005_remove_messages_addressee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='addressee',
            new_name='to',
        ),
    ]
