# Generated by Django 4.1.5 on 2023-01-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0006_rename_addressee_messages_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='to',
        ),
        migrations.AddField(
            model_name='messages',
            name='addressee_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='owner_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
