# Generated by Django 4.1.5 on 2023-01-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0008_remove_messages_addressee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='owner',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='messages',
            name='to',
            field=models.CharField(default='', max_length=20),
        ),
    ]
