# Generated by Django 4.1.5 on 2023-02-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0010_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='picture',
            field=models.ImageField(upload_to='uploads/%y'),
        ),
    ]
