# Generated by Django 4.1.5 on 2023-02-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0011_alter_pizza_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='picture',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
