# Generated by Django 4.1.5 on 2023-02-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0012_pizza_name_alter_pizza_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(default=None, max_length=12)),
                ('product_id', models.IntegerField(default=None)),
            ],
        ),
    ]
