# Generated by Django 4.1.5 on 2023-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0013_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.JSONField(default=None),
        ),
    ]
