# Generated by Django 4.1.5 on 2023-02-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0014_alter_order_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
