# Generated by Django 4.1.5 on 2023-02-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0015_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='user_ip',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
