# Generated by Django 4.1.5 on 2023-02-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0017_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='offered',
            name='user_address',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
