# Generated by Django 4.1.5 on 2023-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0018_offered_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offered',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
