# Generated by Django 4.1.5 on 2023-02-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0019_alter_offered_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offered',
            name='date_time_stop',
            field=models.DateTimeField(null=None),
        ),
    ]
