# Generated by Django 4.1.5 on 2023-02-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0022_offered_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offered',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
