# Generated by Django 4.1.5 on 2023-02-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0023_offered_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offered',
            name='status',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
