# Generated by Django 4.1.5 on 2023-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0024_alter_offered_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offered',
            name='status',
        ),
        migrations.AddField(
            model_name='offered',
            name='order_status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
