# Generated by Django 4.1.5 on 2023-02-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsite', '0025_remove_offered_status_offered_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offered',
            name='order_status',
        ),
        migrations.AddField(
            model_name='offered',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
